name: sales-forecast-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - xgboost==2.0.3
    - lightgbm==4.3.0
    - scikit-learn==1.4.1
    - numpy==1.26.4
    - pandas==2.2.1
    - shap==0.45.0
    - mlflow==2.11.1
    - azureml-defaults
